id: P009486
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS20655
  title: ཐ་སྨན་ནམ་གཏེར་སྨན་སྐོར།
  author: ''
  volumes:
    14b59dab4411411eb4290b53cff7ddc1:
      image_group_id: I8LS20657
      title: ''
      volume_number: 1
      total_pages: 420
      base_file: v001.txt
